### ISSUE TITLE
plans to support REST API?

### ISSUE THREAD

**Issue by matsu-chara** [yahoo/kafka-manager#114]
Hi, 
I'm using kafka-manager via browser.
But, I also want to use it via curl or any other services.

Do you have plans to support REST API?, like
[kafka-rest](https://github.com/confluentinc/kafka-rest/wiki/Project---Admin-APIs) or [burrow](https://github.com/linkedin/Burrow/wiki/HTTP-Endpoint)

**Comment by jisookim0513** [comment]
There are a few REST API for kafka-health-checking (you can find them in routes, under /api/status/..). I plan to add REST API for adding partitions and maybe reassigning partitions, but probably not within a month.

**Comment by matsu-chara** [comment]
Ok! I will wait it.
Thanks!

**Comment by rachana-prajapati** [comment]
Any REST apis exposed for Kafka manager? If so can you please provide the link for the documentation.
Thanks
