### ISSUE TITLE
Feature Ask: Provide Web API for getting the data

### ISSUE THREAD

**Issue by tonyxuqqi** [yahoo/kafka-manager#124]
Hi, 
Currently the Kafka-Manager is a great management console. It will be even greater if it could provide the web api to expose the data shown in the UI. 
We like to integrate it with our monitoring & alert system.

**Comment by patelh** [comment]
Which specific data are you looking for?

**Comment by patelh** [comment]
The following APIs are already available.  If you need more, please create a new issue with detailed requirements:

GET         /api/status/:c/brokers
GET         /api/status/:c/topics
GET         /api/status/:c/:t/underReplicatedPartitions
GET         /api/status/:c/:t/unavailablePartitions
