### ISSUE TITLE
kafka manager cannot specify the database

### ISSUE THREAD

**Issue by tonyxuqqi** [yahoo/kafka-manager#127]
Try to specify database like this:
db.default.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.default.url="jdbc:sqlserver://sqlserver:1433;databaseName=dbname
db.default.user="sa"
db.default.password="password"

But it never actually uses the setting at all.

**Comment by patelh** [comment]
Kafka manager does not use any database.   Do not change the default DB settings.

**Comment by bergbrains** [comment]
What's the intended purpose of having these variables in the default config file if they are not used?

**Comment by patelh** [comment]
The conf file was the default one provided by play.  They've been removed in #169
