### ISSUE TITLE
how to add cluster

### ISSUE THREAD

**Issue by rycoxiao** [yahoo/kafka-manager#13]
hi:
I start the server succeed.
![kafkamanager1](https://cloud.githubusercontent.com/assets/10862900/6076077/075eb410-ae19-11e4-91fe-2fd7ccc091ad.jpg)

but when I add a kafka cluster config, then failed,error info below:
Yikes! Ask timed out on [ActorSelection[Anchor(akka://kafka-manager-system/), Path(/user/kafka-manager)]] after [1000 ms] Try again.
![kafkamanager1](https://cloud.githubusercontent.com/assets/10862900/6076112/7e9c32d2-ae19-11e4-8225-6260cf24c463.jpg)

**Comment by rycoxiao** [comment]
patch command line error:
[error] k.m.ApiError - error : Ask timed out on [ActorSelection[Anchor(akka://kafka-manager-system/), Path(/user/kafka-manager)]] after [1000 ms]
akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://kafka-manager-system/), Path(/user/kafka-manager)]] after [1000 ms]
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333) ~[com.typesafe.akka.akka-actor_2.11-2.3.7.jar:na]
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117) ~[com.typesafe.akka.akka-actor_2.11-2.3.7.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599) ~[org.scala-lang.scala-library-2.11.4.jar:na]
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[org.scala-lang.scala-library-2.11.4.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597) ~[org.scala-lang.scala-library-2.11.4.jar:na]

**Comment by alexander-pospiech-inovex** [comment]
Hi,
I had something very similar yesterday, when I started to use kafka manager.
Is your Zookeeper cluster running, please check the logging in the zookeeper.out and are the ZK nodes correctly specified in the application.conf?
best regards,
alex

**Comment by rycoxiao** [comment]
hi: 
alexander
my zookeeper cluster is not only service for kafka,but also include hbase.
and my web-console and offsetmonitor server is normal.
I think it not problem for zookeeper.

**Comment by DeanHere** [comment]
just in case, you would have to check if the port is opening for your manager, may be a firewall issue?

**Comment by rycoxiao** [comment]
hi:
DeanHere
I have open the website:http://server-04:60003/addCluster.

**Comment by myhero520** [comment]
I have the same problem with you, how to deal with it ?

**Comment by alexander-pospiech-inovex** [comment]
1. Please check wether your DNS is working for your cluster, e.g. ping server-04 from server-03.
2. Please check the log files  (zookeeper.out) on every ZK node for errors. 
3. Connect to ZK 
  $ <path/to/zookeeper>/bin/zkCli.sh -server server-04:2181,server-03:2181,server-02:2181
4. Is your Kafka Server up and running? Please check if the kafka processes are running and have a look in the log files on each broker node.

**Comment by myhero520** [comment]
@ alexander-pospiech-inovex  , sorry ,my kafka Server and zookeeper are running , and there is no errors exits.
this problem looks like the same to issues 11, I use the commond line -Dkafka-manager.zkhosts="server-04:2181" and then the kafka-manager is started successfully,

and for a second , i get into the host.com:9000/addCluster successfully too !

**Comment by alecinvan** [comment]
Here is my problem, when I install kafka-manager on one of my Dev node, it works fine. But I want it to work out-of-box, so I install it on a vagrant VM, then I got same error: 

 Yikes! Ask timed out on [ActorSelection[Anchor(akka://kafka-manager-system/), Path(/user/kafka-manager)]] after [1000 ms] Try again. 


I confirm, zkEnsemble and kafka nodes are all working fine. How to solve it?

**Comment by patelh** [comment]
Hi guys, anyone still having a problem getting it running?  Please do email me at hiral@yahoo-inc.com and give me context to what you are trying to do and I will try my best to help.  Thanks!

**Comment by rycoxiao** [comment]
thanks for mhyhero520,I think the problem is the command isn't load the right config file,I read the shell,the config paramter is set script_conf_file="/etc/default/kafka-manager".

**Comment by spuder** [comment]
+1

The solution is to change the /etc/init/kafka-manager.conf script from this


```
script
  exec sudo -u kafka-manager bin/kafka-manager
end script
```

To this

```
script
  exec sudo -u kafka-manager bin/kafka-manager -Dconfig.file=/etc/kafka-manager/application.conf
end script
```

**Comment by jianchen2580** [comment]
+1 - kafka-manager v1.3.0.4
Can't enter topics.
`k.m.ApiError$ - error : Ask timed out on [ActorSelection[Anchor(akka://kafka-manager-system/), Path(/user/kafka-manager)]] after [5000 ms]`
