### ISSUE TITLE
default api timeout setting is not proper on startup

### ISSUE THREAD

**Issue by fujohnwang** [yahoo/kafka-manager#14]
default is 1000 milli, better make it longer.

although users can configure it themselves, but a proper default is better.

**Comment by rycoxiao** [comment]
because the shell not read the wrong config file, i think it the shell bug.
you can use the command 'cat' to check the kafka-manager shell,the config file is set belowdeclare -r script_conf_file="/etc/default/kafka-manager"

**Comment by patelh** [comment]
Default has been increased to 5 secs.  You can set it yourself in conf:

kafka-manager.api-timeout-millis=10000
