### ISSUE TITLE
Basic authentication support

### ISSUE THREAD

**Issue by sslavic** [yahoo/kafka-manager#141]
Please consider adding basic authentication support.

**Comment by xuwei-k** [comment]
https://github.com/yahoo/kafka-manager/issues/111 duplicate?

**Comment by sslavic** [comment]
The other ticket mentions oauth2. This one is IMO less demanding, could be a good start. Preferably both get supported.

**Comment by MichaelScofield** [comment]
+1!

**Comment by Justwin-zyq** [comment]
+ 1 !

**Comment by MarMarAba** [comment]
+1

**Comment by sslavic** [comment]
Fixed by https://github.com/yahoo/kafka-manager/pull/217
