### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by EamonZhang** [yahoo/kafka-manager#149]
in home page document 
$ PATH=/usr/local/oracle-java-8/bin:$PATH \
  JAVA_HOME=/usr/local/oracle-java-8 \
  /path/to/sbt -java-home /usr/local/oracle-java-8 dist clean

use
 /path/to/sbt -java-home /usr/local/oracle-java-8 clean dist 
instead of !!!

**Comment by zheolong** [comment]
@EamonZhang `sbt dist clean` is just fine.
