### ISSUE TITLE
A question about delete topic

### ISSUE THREAD

**Issue by TimeEraser** [yahoo/kafka-manager#164]
KafkaCommandActor
----------------------------
 case KCDeleteTopic(topic)   =>
    ..........
kafkaCommandActorConfig.adminUtils.deleteTopic(kafkaCommandActorConfig.curator, topic) 
         kafkaCommandActorConfig.curator.delete().deletingChildrenIfNeeded().forPath(ZkUtils.getTopicPath(topic))
    ..........
Actually ， if you want to delete the topic ， adding the path "/admin/delete_topics/$topics"in the zookeeper will effectively work ！
---------------------------
why do you delete the path “brokers/topics/$topic” again ?
---------------------------

**Comment by TimeEraser** [comment]
I'm not sure that if the prolbem leading to the strange phenomenon that though the brokers have already delete the topic successfully ， the zookeeper  will leave the topic path behind ，or not .

**Comment by patelh** [comment]
Good catch.  This was left over code from 0.8.1.1 support for delete topic.
