### ISSUE TITLE
Can kafka-manager automatically detect the consumer offsets' saving places? zk or kafka?

### ISSUE THREAD

**Issue by WanliTian** [yahoo/kafka-manager#165]
I want to use kafka-manager to monit my kafka cluster, and i save consumer offsets in kafka. Can i use kafka-manager now? I cannot find any config for this. Can kafka-manager detect it automatically?

**Comment by patelh** [comment]
This is WIP.  Hopefully soon.

**Comment by DavidLiuXh** [comment]
Simply use AdminClient class in the new kafka sdk 0.9.0.0 to get commited offset in the kafka broker.
