### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by mydiemho** [yahoo/kafka-manager#175]
Every so often, my kafka-manager instances reach critical level CPU usage and I would have to restart the instances.  

I have both 16 and 32 cores running on Ubuntu 12.04.5 LTS.

**Comment by patelh** [comment]
How large are you kafka clusters?

**Comment by mydiemho** [comment]
I have 4 clusters:

(1) 16 topics, 3 brokers
(2) 112 topics, 3 brokers
(3) 7 topics, 3 brokers
(4) 3 topics, 3 brokers

Are there specific information you are looking for?

**Comment by patelh** [comment]
what version of kafka manager are you using?

**Comment by mydiemho** [comment]
1.2.9.10

**Comment by patelh** [comment]
Please upgrade to 1.3.0.4 and please adjust these settings as indicated in the README:

Consider setting these parameters for larger clusters with jmx enabled :

    kafka-manager.broker-view-thread-pool-size=< 3 * number_of_brokers>
    kafka-manager.broker-view-max-queue-size=< 3 * total # of partitions across all topics>
    kafka-manager.broker-view-update-seconds=< kafka-manager.broker-view-max-queue-size / (10 * number_of_brokers) >

Here is an example for a kafka cluster with 10 brokers, 100 topics, with each topic having 10 partitions giving 1000 total partitions with JMX enabled :

    kafka-manager.broker-view-thread-pool-size=30
    kafka-manager.broker-view-max-queue-size=3000
    kafka-manager.broker-view-update-seconds=30

You may also want to increase the above three if you have consumer polling enabled depending on the # of consumers you have reporting through Zookeeper.

**Comment by patelh** [comment]
Release 1.3.0.7 exposes many of the above settings through the UI now so you can adjust it directly.

**Comment by mydiemho** [comment]
@patelh I have upgraded to 1.3.0.8.  However, I don't see the UI that you're talking about.  Could you screen shot so I know what you are referring to?  Thanks
