### ISSUE TITLE
Cluster already exists?

### ISSUE THREAD

**Issue by PenGCanNtFly** [yahoo/kafka-manager#179]
Hi:
     I need some help to run kafka-manager success,Thanks...
    ***Kafka-manager Version : 1.2.9.13/14***
    (1) After i added a new cluster,the list of kafka-manager doesn't show the new cluster  witch i made before,until i restart kafka-manager.
    (2) An exception came out from kafka-manager like : ***"Yikes! Ask timed out on [ActorSelection[Anchor(akka://kafka-manager-system/), Path(/user/kafka-manager)]] after [5000 ms]"***, when i check Cluster ***Topics/test2***,but the other one***(Topics/test1)*** is right.
    (3)
![kafka-manager-github](https://cloud.githubusercontent.com/assets/16128503/11801882/f1f5175c-a324-11e5-8149-d8e72ee42fb5.png)

**Comment by Penguicannotfly** [comment]
second question could be solved by : #143

**Comment by patelh** [comment]
The consumer polling has been disabled by default, it was too aggressive and didn't work right for large clusters.  Please try 1.3.0.4.  There is a hard java 8 requirement now.
