### ISSUE TITLE
binary release would be awesome!

### ISSUE THREAD

**Issue by mikedanese** [yahoo/kafka-manager#18]
A binary release of this as an executable jar would be awesome! I'd love to try this but I'm not very familiar with the scala toolchain and I'm working through some difficulties with sbt (which I attribute to operator error). Thanks, this kafka-manager looks very cool.

**Comment by mulloymorrow** [comment]
+1

**Comment by wangqj** [comment]
+1

**Comment by Rigoberto-Vazquez** [comment]
+1

**Comment by Dinoshauer** [comment]
+1

**Comment by raags** [comment]
+1

**Comment by mazhechao** [comment]
+12306

**Comment by qoomon** [comment]
+1

**Comment by haosdent** [comment]
+1

**Comment by rvantassell** [comment]
It would at least be nice to support/supply not only the *.zip, but the *.rpm and *.deb packages. Especially since, currently, the rpm-build part of the package seems broken.

**Comment by msilvey** [comment]
https://github.com/yahoo/kafka-manager/pull/35 has been filed for this.  Docs will be needed but, basically, it will enable the option of './sbt clean assembly' generating a standalone jar.

**Comment by rvantassell** [comment]
I've opened a separate issue #36 to help track the RPM Build fix (along with an example of working around it, for now).

**Comment by spuder** [comment]
There is now a way to create .deb and .rpm files

```
sbt debian:packageBin

sbt rpm:packageBin
```

It would be great if we could get these hosted on package cloud. 

https://packagecloud.io/

Then puppet/chef/ansilbe/salt could always make sure that the latest version of kafka-manager is installed.

**Comment by spuder** [comment]
I went ahead and created .deb packages for a few of the more recent releases and uploaded them to package cloud. (PM me if you have .rpms, I don't have time/need to compile them manually)

https://packagecloud.io/spuder/kafka-manager

It would be super trivial to automate this so that travis CI automatically uploads to packagecloud every time a new build is released. [Packagecloud has the steps documented here:](https://packagecloud.io/docs#travis)

@mikedanese I'm willing to do the work on this if you'll just enable travis and create a more official pakcagecloud account. There are a fair amount of people who don't want to compile every time a new build is released.

**Comment by spuder** [comment]
@bmillemathias I've uploaded kafka-manager 1.3.0.7 and 1.3.0.8 for ubuntu 14.04. Give them a try. I haven't tested them.

**Comment by bmillemathias** [comment]
@spuder Thanks a lot, I'm in vacation right now but give a try with the latest version when I'll be back at work.

**Comment by tintojames** [comment]
Thank you..  I have used this and works like a charm

**Comment by raulvc** [comment]
I've packaged an rpm for release 1.3.1.8, you may find it here:
https://packagecloud.io/raul_cioldin/rhel7/packages/fedora/23/kafka-manager-1.3.1.8-1.noarch.rpm

**Comment by jorgheymans** [comment]
@raulvc links seems to have gone missing, is it available anywhere else ?

**Comment by raulvc** [comment]
@jorgheymans:
https://drive.google.com/file/d/0B7XRzO9MVPpNcFdCbkNmME5BVEU/view?usp=sharing

**Comment by vishnuprabhu-g** [comment]
+1

**Comment by stduolc** [comment]
+1

**Comment by sherry0429** [comment]
+1

**Comment by pcpshephertz** [comment]
+1

**Comment by garyelephant** [comment]
+1

**Comment by yluom** [comment]
+1

**Comment by acbox** [comment]
+1

**Comment by jjoller** [comment]
+1

**Comment by lonerzzz** [comment]
+1

**Comment by mcimbora** [comment]
+1

**Comment by edperry** [comment]
any progress on this as it is an issue that has been open since 2015.

**Comment by bm34943** [comment]
+1

**Comment by mahieddine-ichir** [comment]
+1

**Comment by SuilAmhain** [comment]
+1 please
Getting sbt 0.13.9 to work/install behind a corporate f/w is unfortunately frustrating.

**Comment by linehrr** [comment]
@SuilAmhain  there is always a choice to use docker, and here is the docker image release: https://hub.docker.com/r/kafkamanager/kafka-manager

**Comment by disizjay** [comment]
I have uploaded the build files, RPM and DEB packages
https://github.com/disizjay/kafka-manager

**Comment by chines** [comment]
> I have uploaded the build files, RPM and DEB packages
> https://github.com/disizjay/kafka-manager

I downloaded the RPM from here and it doesn't validate as an RPM.  ?

**Comment by disizjay** [comment]
You mean the RPM was broken ? I will fix that if it was broke. 

But for now you can use the after build binary files to run kafka-manager script to start the service.

**Comment by blaghed** [comment]
+1
