### ISSUE TITLE
How to change the timeout parameters?

### ISSUE THREAD

**Issue by panda87** [yahoo/kafka-manager#180]
Im getting to many `Yikes! Ask timed out on [ActorSelection[Anchor(akka://kafka-manager-system/), Path(/user/kafka-manager)]] after [5000 ms]`

And I want to know if I can provide another values to the timeout params?
Im using Docker container for that, so env var are preferred.

Thanks

**Comment by Penguicannotfly** [comment]
:+1:

**Comment by DavidLiuXh** [comment]
Set kafka-manager.api-timeout-millis=xxx in the application.conf

**Comment by panda87** [comment]
Thanks @DavidLiuXh 
There are another timeout params we can set in?

D.

**Comment by DavidLiuXh** [comment]
@panda87 
They in this KafkaManager.scala
BaseZkPath -> KafkaManagerActor.ZkRoot,
      PinnedDispatchName -> "pinned-dispatcher",
      BrokerViewUpdateSeconds -> "10",
      KafkaManagerUpdateSeconds -> "10",
      DeleteClusterUpdateSeconds -> "10",
      DeletionBatchSize -> "2",
      MaxQueueSize -> "100",
      ThreadPoolSize -> "2",
      MutexTimeoutMillis -> "4000",
      StartDelayMillis -> "1000",
      ApiTimeoutMillis -> "5000",
      ClusterActorsAskTimeoutMillis -> "2000",
      PartitionOffsetCacheTimeoutSecs -> "5",
      SimpleConsumerSocketTimeoutMillis -> "10000"

**Comment by patelh** [comment]
I've add some of the important ones to the readme for 1.3.0.4

**Comment by panda87** [comment]
Thanks @DavidLiuXh

**Comment by patelh** [comment]
Can this be closed?

**Comment by panda87** [comment]
Sure
