### ISSUE TITLE
Could not get offset when using KafkaUtils.createDirectStream with Spark Streaming

### ISSUE THREAD

**Issue by shenzhun** [yahoo/kafka-manager#207]
Hi there,
spark version: 1.6.0
scala: 2.10.4
EMR: 4.3.0

When I use KafkaUtils.createDirectStream with Spark Streaming to consumer data from Kafka, I could not see the consumer info from Kafka Manager.

Here is my setting code:
 ````scala
  val kafkaParams = Map[String, String]("bootstrap.servers" -> brokers, "group.id" -> "ss-test1")
  val topicsSet = topics.split(",").toSet
  val instream = KafkaUtils.createDirectStream[String, String, StringDecoder, StringDecoder](ssc, kafkaParams, topicsSet)
```

Thanks!

**Comment by mariussoutier** [comment]
DirectStream does not use ZooKeeper...

**Comment by shenzhun** [comment]
You're right! But Kafka Manager supports 0.9.0.0, it should be OK for us to get the consumer group offset of Kafka (new consumer).

**Comment by mariussoutier** [comment]
Spark doesn't use the new consumer :) It saves the offsets in the checkpoint.

**Comment by shenzhun** [comment]
I recheck the DirectStream details, as you said it saves the offsets in the checkpoint. It also provide a way to update Zookeeper by myself, but I could not understand it. Any advice ?

**Comment by mariussoutier** [comment]
You have to update ZooKeeper from code, check the HasOffetRange part in the official Spark Kafka documentation.

**Comment by patelh** [comment]
@shenzhun please close if this is no longer an issue.
