### ISSUE TITLE
Does kafka-manager support ssl?

### ISSUE THREAD

**Issue by ffirewy** [yahoo/kafka-manager#208]
In my kafka config/server.properties,listeners = SSL ://: 9092;PLAINTEXT ://: 9093

But in kafka manager,when I try to get the port,I can only get 9093

**Comment by Labibme** [comment]
Hi, 
i have same issue, i tried "SSL" and tool stop detecting lag and offset...

**Comment by jsargiot** [comment]
Hey @Labibme, I think your problem might be solved once https://github.com/yahoo/kafka-manager/pull/532 gets merged
