### ISSUE TITLE
Could u support version 0.9.0.0?

### ISSUE THREAD

**Issue by Acceml** [yahoo/kafka-manager#209]

**Comment by ffirewy** [comment]
Branch 'upload-to-90' supports 0.9.0.0 and 0.9.0.1

**Comment by patelh** [comment]
Planning to get it merged this week to master.

**Comment by zhjt80** [comment]
Great, waiting for the release

**Comment by yayuntian** [comment]
expect

**Comment by evandun** [comment]
expect

**Comment by salekseev** [comment]
+1

**Comment by cckumarr** [comment]
+1

**Comment by bwzhang2011** [comment]
any update with such issue ?

**Comment by ldebowczyk** [comment]
Are there any plans to use new consumer implementation for consumer offsets fetching? Our installation is secured with SSL, and only new consumer implementation supports it. So we can't use current version of Kafka Manger with our installation.

**Comment by minhdanh** [comment]
@patelh is there any update on this, please?

**Comment by jarkomes** [comment]
+1

**Comment by xuwei-k** [comment]
duplicate https://github.com/yahoo/kafka-manager/issues/189

**Comment by xuwei-k** [comment]
https://github.com/yahoo/kafka-manager/pull/195

**Comment by patelh** [comment]
This has been merged into master and released as tag 1.3.0.7
