### ISSUE TITLE
Incorrect ZK data structure for topic config changes

### ISSUE THREAD

**Issue by kjvalencik** [yahoo/kafka-manager#210]
The `upgrade-to-90` branch creates invalid ZK data data structures in `/config/changes`. The format of these changed in `0.9` from a string to a JSON object.

https://cwiki.apache.org/confluence/display/KAFKA/Kafka+data+structures+in+Zookeeper#KafkadatastructuresinZookeeper-0.9.0

The following line will need to be updated:
https://github.com/yahoo/kafka-manager/blob/upgrade-to-90/app/kafka/manager/utils/AdminUtils.scala#L272

Expected Value: `{"version":1,"entity_type":"topics","entity_name":"topicName"}`
Actual value: `"topicName"`

**Comment by patelh** [comment]
Thanks for the fix and it is now pushed into master!
