### ISSUE TITLE
Kafka Version : How to set version to 0.9.x

### ISSUE THREAD

**Issue by abtpst** [yahoo/kafka-manager#213]
In the add cluster window, i can only select upto version 0.8.2.2. But i have Kafka version 0.9.x. How do i specify this?

**Comment by gpatwa** [comment]
0.9.x support is in-progress

https://github.com/yahoo/kafka-manager/pull/195

**Comment by patelh** [comment]
This has been merged into master and released as tag 1.3.0.7
