### ISSUE TITLE
upgrading to 1.3.0.7

### ISSUE THREAD

**Issue by analog76** [yahoo/kafka-manager#220]
I am upgrading to 1.3.0.7 from 1.2. I am able to build successfully but while deploying I am getting Injection error. 

Kafka version 
Kafka	0.8.1.2.2	

/mnt/data/softwares/kafka-manager-1.3.0.7/bin/kafka-manager -Dconfig.file=/mnt/data/softwares/kafka-manager-1.2.9.12/conf/application.conf  
Oops, cannot start the server.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Could not find a suitable constructor in controllers.Application. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Application.class(Application.scala:16)
  while locating controllers.Application
    for parameter 1 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

2) Could not find a suitable constructor in controllers.Cluster. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Cluster.class(Cluster.scala:28)
  while locating controllers.Cluster
    for parameter 2 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

3) Could not find a suitable constructor in controllers.Consumer. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Consumer.class(Consumer.scala:16)
  while locating controllers.Consumer
    for parameter 5 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

4) Could not find a suitable constructor in controllers.Logkafka. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Logkafka.class(Logkafka.scala:33)
  while locating controllers.Logkafka
    for parameter 4 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

5) Could not find a suitable constructor in controllers.PreferredReplicaElection. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.PreferredReplicaElection.class(PreferredReplicaElection.scala:26)
  while locating controllers.PreferredReplicaElection
    for parameter 6 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

6) Could not find a suitable constructor in controllers.ReassignPartitions. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.ReassignPartitions.class(ReassignPartitions.scala:27)
  while locating controllers.ReassignPartitions
    for parameter 7 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

7) Could not find a suitable constructor in controllers.Topic. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Topic.class(Topic.scala:33)
  while locating controllers.Topic
    for parameter 3 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

8) Could not find a suitable constructor in controllers.api.KafkaStateCheck. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.api.KafkaStateCheck.class(KafkaStateCheck.scala:19)
  while locating controllers.api.KafkaStateCheck
    for parameter 8 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

8 errors
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321)
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:316)
	at play.api.Application$class.routes(Application.scala:112)
	at play.api.DefaultApplication.routes(Application.scala:241)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:90)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:87)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:87)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:87)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:54)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)

**Comment by patelh** [comment]
Your config files is outdated.  You use the new config file with 1.3.0.7 and make the changes you make to 1.2 config file again.

**Comment by analog76** [comment]
Thanks.  It seems I was pointing to wrong config file....

It resolved the issue.
