### ISSUE TITLE
Converting zkHosts to lowercase cause problem when zkHosts contains uppercase chroot path

### ISSUE THREAD

**Issue by evanmeng** [yahoo/kafka-manager#23]
`KafkaManager` will convert cluster name and zkHosts to lowercase when constructing a `ClusterConfig`.
This works fine if zkHosts only contains host names and ports, however, it also may contain additional chroot path at its end.
In such cases, the chroot path means a part of a ZNode path, which is case sensitive. Converting it to lowercase will make Kafka Manager refer to a non-existed path on Zookeeper when operating the cluster.

To me, the case conversion is not quite meaningful, even cluster name is not necessarily to be in lowercase. Can we just keep the casings of names and zkHosts as they are given?

-----------------
How to reproduce

1. Add a kafka cluster whose zookeeper hosts contains chroot path with uppercase letters. Like `
zkhost1:2181,zkhost2:2181,zkhost3:2181/KafkaClusterPath`
1. The cluster will be added successfully and listed in cluster list.
1. Clicking the name of the new added cluster will show you the error.

---------------------------

I tried get rid of the to lowercase conversion in my forked repo 
https://github.com/evanmeng/kafka-manager/commit/9070032d26d72a31c8cb478defb548c0377906b8
and looks things work fine.

But I am not sure whether this will break other functions since there is no regression tests yet. Maybe some of you can have a look at it?

**Comment by patelh** [comment]
This has been fixed.
