### ISSUE TITLE
Support for kafka 0.9.0.1

### ISSUE THREAD

**Issue by eripe970** [yahoo/kafka-manager#231]
Hi, 

Is this tool supporting kafka 0.9.0.1? 

If it is then I think that https://github.com/yahoo/kafka-manager/blob/master/README.md needs to be updated.

**Comment by patelh** [comment]
Yes, you're right, readme is out of date.

**Comment by eripe970** [comment]
Fix in https://github.com/yahoo/kafka-manager/pull/232

**Comment by bric3** [comment]
This issue may be closed then ;)
