### ISSUE TITLE
where do we configure application.home

### ISSUE THREAD

**Issue by rudrasharma** [yahoo/kafka-manager#255]
After running the kafka manager following the instructions provided i see the following directory created in the kafka-manager install directory application.home_IS_UNDEFINED. I could not find where this variable is set.

**Comment by rudrasharma** [comment]
Apparently it is just a java argument when we run the kafka manager, this should be in the instructions as it could throw off a lot of new users:
bin/kafka-manager -Dconfig.file=/var/kafka-manager-1.3.0.4/conf/application.conf -Dapplication.home=/var/kafka-manager-1.3.0.4)

**Comment by FunkyYang** [comment]
no files can write this?I tried writed in application.conf and it's doesn't work

**Comment by rudrasharma** [comment]
Not sure I understand your issue @FunkyYang. Are you having the same problem, or you don't think the problem exists?

**Comment by FunkyYang** [comment]
I had sloved this problem ,Thanks

**Comment by xrewndel** [comment]
@FunkyYang How did you solve this?

**Comment by hackeys** [comment]
while running kafka-manager.sh . Pass an argument -Dapplication.home=/path/to/kafkamanager
