### ISSUE TITLE
Issue when attempting manual partition assignment

### ISSUE THREAD

**Issue by metalseargolid** [yahoo/kafka-manager#264]
When I use Kafka Manager to manually assign a partition, I get a successful message, but the topic partition is never assigned to the broker I selected, and there is no indication in my Kafka Broker logs that any reassignment has taken place.

**Comment by patelh** [comment]
Manual assignment just updates the saved assignments in ZK by KM.  Once this is done.  You need to run reassignment.

**Comment by metalseargolid** [comment]
Forgot to update, but your advice worked!
