### ISSUE TITLE
how to bind mutiple kafka manager to one zookeeper

### ISSUE THREAD

**Issue by gengweifeng** [yahoo/kafka-manager#277]
excuse me:
  i want deploy mutiple kafka manager instance, but make these KM use one zookeeper. just like mutiple kafka use one zookeeper.
  when i make mutiple kafka use one zookeeper, i can set **zookeeper.connect=localhost:2181/kafka1**, another **zookeeper.connect=localhost:2181/kafka2** in the kafka **server.properties**. and the zookeeper dir become **/kafka** and **/kafka2**.
now what should i do? can multiple KM use one zookeeper release?
thank you!

**Comment by DavidLiuXh** [comment]
set kafka-manager.base-zk-path int application.conf
