### ISSUE TITLE
When it can support kafka 0.8.0?

### ISSUE THREAD

**Issue by buhe** [yahoo/kafka-manager#3]
Hi 

When it can support kafka 0.8.0?

thx

**Comment by patelh** [comment]
No plans to support older versions of Kafka.  However, I am not sure if there are any Zookeeper specific changes between 0.8.0 and 0.8.1.1.  Meaning you may be able to add your cluster as 0.8.1.1.  Try it out on a dev cluster.

**Comment by buhe** [comment]
I try it on our prod cluster , Awesome ！

thanks
