### ISSUE TITLE
Support for viewing existing clusters

### ISSUE THREAD

**Issue by jlintz** [yahoo/kafka-manager#30]
Just got kafka manager up and running and realized I have no ability to specify a root node in zookeeper for the manager to look in.  We have a couple of existing clusters under a couple of different nodes in zookeeper that I'd love to add into the manager but don't see a way to currently do this

**Comment by spuder** [comment]
You can manage multiple clusters, but you have to add them one at a time. 

When adding the zookeepr hosts, simply add the chroot to the end. 


    zoo01:1234,zoo02:1234/kafka-cluster1

and 

    zoo01:1234,zoo02:1234/kafka-cluster2

![screenshot 2015-03-09 13 27 09](https://cloud.githubusercontent.com/assets/242382/6562578/02bc0f66-c660-11e4-92bc-86f2bfb93342.png)

![screenshot 2015-03-09 13 26 06](https://cloud.githubusercontent.com/assets/242382/6562560/df9dafda-c65f-11e4-8f4c-219571399819.png)

**Comment by jlintz** [comment]
@spuder ah thanks, this won't modify the existing cluster in any way when I add it?

**Comment by spuder** [comment]
All it does is query zookeeper. I don't believe it makes any changes to kafka itself, however it does create a new chroot in zookeeper called 'kafka-manager'.

**Comment by jlintz** [comment]
Awesome, it worked, thanks!
