### ISSUE TITLE
Is Kafka Topic Offset and Consumer group disabled for a secure cluster

### ISSUE THREAD

**Issue by Ashish123gs** [yahoo/kafka-manager#310]
I upgraded Kafka Manager from 1.3.0.8 to 1.3.1.8 and then i am unable to see topic offset details and consumer group info ?

Cluster version is 0.9.0.1

Is this expected ?

**Comment by tanuj83** [comment]
I also faced same issue

**Comment by jammann** [comment]
Experienced the same issue (with a 0.10.1.1 cluster and KafkaManager with the 0.10 pull request). With a fully secured cluster (only SSL Kakfa listener), Kafka Manager was able to connect (with a correct consumer.properties file). It also showed **some** consumer information, namely the consumer group, consumer name and consumer offset per partition.

But I was never able to get it also to read and display the current Topic offset and in consequence no lag was shown.

I had to revert to configure Kafka with 2 listeners (an additional plaintext one). Only then would Kafka Manager show all consumer information

**Comment by Ashish123gs** [comment]
Thats right .
We use kerberos SASL .
The problem with that approach is that we have to give read permission for the plain text listener to access the topic offset and consumer offset and display lag .
giving read only permission means to open the topic for unauthorized users

**Comment by jammann** [comment]
I just don't understand why Kafka Manager can retrieve SOME information via a SSL connection but not ALL. I guess I need to dig into the code a bit

**Comment by Ashish123gs** [comment]
Hi,

Any tricks ?

I see with new KM version 1.3.3.4 , if a kafka cluster has both SASL and PLAINTEXT ports open , then KM always uses the SASL port , i tried the consumer property to force it to use the PLAINTEXT port but no luck .

**Comment by tanuj83** [comment]
I am also facing same issue, my kafka cluster has both PLAINTEXT and SSL enabled but KM connects to 9093 SSL port only and even on passing truststore cert, it is not connecting to broker at port 9093
Tested on 1.3.3.6 and 1.3.3.7

**Comment by tanuj83** [comment]
Okay for both plaintext and SSL, I changed broker listeners in kafka properties in an order.
listeners = PLAINTEXT://FQDN:9092,SSL://FQDN:9093,
then it is working as it connects to 9092 now.

I checked in ZK, broker information, it had default SSL then PLAINTEXT but it was open port 9092 as well, it seems KM takes 1st defined port in ZK and doesn't try PLAINTEXT on failure

**Comment by Ashish123gs** [comment]
I did a bit of tests and below ticket has more details about this problem

https://github.com/yahoo/kafka-manager/issues/368

**Comment by patelh** [comment]
Latest version you can configure security protocol per cluster in cluster config.

**Comment by Ashish123gs** [comment]
Awesome .

Can we do some documentation how to configure a secured cluster in KM please  ?

it will help to get started quickly.

**Comment by patelh** [comment]
Yes, will add some notes.

**Comment by Ashish123gs** [comment]
Cool , thanks

**Comment by tanuj83** [comment]
@patelh it works great as see that it connects to all available listeners of brokers now. 
Question, if we have only SSL with client auth required Kafka cluster, in that case, where to put certificate? all clusters trustcerts should be in single cert ?

**Comment by jerryldh** [comment]
I tried to add related security config to "consumer.properties" in MK_HOME/config, BUT it doesn't work anyway.

**Comment by jerryldh** [comment]
@tanuj83 Have you solved this problem?

**Comment by tanuj83** [comment]
@jerryldh I am using 1.3.3.11 version and it has option at cluster modify to select "Security Protocol". I just selected SSL and it is working good. I see also on brokers, and my broker has connection to Kafka manager servers with 9093,2181 port only.

Do we really need Cert?  if yes why, it is metrics data not producer/consumer data

**Comment by jerryldh** [comment]
@tanuj83 Thanks，i update KM to 1.3.3.13， i set Security Protocol as SS. 
Related consumer.properties worked, but it seems that i confused my problem, i still can,t get topic's Latest Offset and Leader Size.
As to "Do we really need Cert?" , my situation is that my kafka cluster only has ssl port, but i still have to manager the cluster by KM, so...

**Comment by Rohlik** [comment]
I set "Security Protocol" to `SSL` in cluster setting, but still I got this error in KM:

**Comment by sparmar123** [comment]
We're using multiple clusters in the same Kafka manager but each one has different SSL cert. How can we configure that ?
