### ISSUE TITLE
Add metrics

### ISSUE THREAD

**Issue by Mogztter** [yahoo/kafka-manager#32]
I think it would be nice to have metrics/stats about Kafka server (message rate, byte in rate, byte out rate...)

AFAIK metrics/stats are not stored in Zookeeper (Ref: https://cwiki.apache.org/confluence/display/KAFKA/Kafka+data+structures+in+Zookeeper). Would you consider a pull request that retrieve metrics from Kafka server ? I could use the [Kafka REST Proxy](http://confluent.io/docs/current/kafka-rest/docs/intro.html), [JMX](http://confluent.io/docs/current/kafka/monitoring.html) or ... ?

A simpler solution might be to get the consumer offset from curator/zookeeper `/consumers/[groupId]/offsets/[topic]/[partitionId]` ?

Wdyt ?

**Comment by patelh** [comment]
This would be great.  Coming from JMX may be better since I'm not sure if the REST Proxy is part of the Apache Kafka distribution or just confluence.

**Comment by Mogztter** [comment]
OK I will open a pull request to discuss implementation details.

**Comment by patelh** [comment]
@Mogztter Thanks for the contrib!  We are using it for our cluster.  Consumer offset watcher would be nice addition too ;)

**Comment by Mogztter** [comment]
You're welcome! I'm glad that you find it useful :)

**Comment by Mogztter** [comment]
I found out that Kafka (core) have an utility class to retrieve consumer offset: https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/tools/ConsumerOffsetChecker.scala

I will do some testing to integrate this utility class :smile:

**Comment by drummerwolli** [comment]
can be closed, or? JXM Metrics are available now in KM ...

**Comment by Mogztter** [comment]
Yes I think we can close this issue now. @patelh Wdyt ?

**Comment by patelh** [comment]
Sure.
