### ISSUE TITLE
Enable JMX Polling ，but don't   display information.

### ISSUE THREAD

**Issue by Songdantes** [yahoo/kafka-manager#339]
![image](https://cloud.githubusercontent.com/assets/12936628/21475809/e0e4dc98-cb6b-11e6-87c6-fd27a8cda8d7.png)

![image](https://cloud.githubusercontent.com/assets/12936628/21475748/df6f2b76-cb6a-11e6-90a8-3f37dfd04922.png)
![image](https://cloud.githubusercontent.com/assets/12936628/21475755/f99388e4-cb6a-11e6-9590-627de778034c.png)
![image](https://cloud.githubusercontent.com/assets/12936628/21475770/45526f98-cb6b-11e6-9d73-4c9d82b532ce.png)

As shown in the figure above， Enable JMX Polling ，but don't   display information  .Has anyone experienced this problem?

my kafka manager version is  “kafka-manager-1.3.0.7”
kafka version is  kafka_2.10-0.8.2.2

**Comment by DavidLiuXh** [comment]
Check /etc/hosts whit 127.0.0.1

**Comment by Songdantes** [comment]
thanks your advise. 

my hosts likes that
cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4

Is  there any  question？

**Comment by DavidLiuXh** [comment]
try to remove this record. @Songdantes

**Comment by Songdantes** [comment]
thanks . I  did  it ，but it still  destn't work.  any other advise?

**Comment by patelh** [comment]
Disable "Display Broker and Topic Size".  Check your logs and see if you see any Exception or ERROR printed.

**Comment by DavidLiuXh** [comment]
Restart kafka-manger after remove this record from /etc/hosts? @Songdantes

**Comment by Songdantes** [comment]
yes ,I restarted it  many times ,but still not work.

**Comment by Songdantes** [comment]
I disable "Display Broker and Topic Size" ,but also didn't  work. @patelh

**Comment by dodysw** [comment]
Have you tried to connect to the JMX port using JConsole and see if it works?

**Comment by Songdantes** [comment]
thanks all,I have sloved this problem,I think the reason why maybe my topic is much,I delete useless topics ，now is ok.
