### ISSUE TITLE
Support deleting partitions and topics

### ISSUE THREAD

**Issue by spuder** [yahoo/kafka-manager#34]
It would be nice to be able to remove partitions and topics from the web interface. (First vote would be for topics).

**Comment by spuder** [comment]
One additional consideration is how do you prevent any user from deleting topics. You could wrap the kafka manager in a proxy, however it would be better to provide a built in authentication mechanism.

**Comment by liuyan3514** [comment]
where is button for remove?

**Comment by patelh** [comment]
Auth is on the table with granular control.  For now, delete topic has been added in #38

**Comment by spuder** [comment]
Dup of #38
