### ISSUE TITLE
consumer tab's information is lost after restart kafka manager 

### ISSUE THREAD

**Issue by KaimingWan** [yahoo/kafka-manager#345]
I find a related issue [#248](https://github.com/yahoo/kafka-manager/issues/248) .

My kafka manager version is 1.3.2.1 which is cloned from [Innometrics/kafka-manager](https://github.com/Innometrics/kafka-manager/tree/master) and supports kafka 0.10.x

My kafka version is kafka 0.10.1.0

I am sure that the consumers are running and I have enable the following items:
1. Enable JMX Polling (Set JMX_PORT env variable before starting kafka server)
2. Poll consumer information (Not recommended for large # of consumers)
3. Filter out inactive consumers
4. Enable Logkafka
5. Enable Active OffsetCache (Not recommended for large # of consumers)
6. Display Broker and Topic Size (only works after applying this patch)

However, the consumer tab shows nothing in kafka manager.

What should I do to fix this problem?

**Comment by KaimingWan** [comment]
I also try to delete the metadata of kafka manager and restart it. However, it didn't make some different.

**Comment by KaimingWan** [comment]
And why "Poll consumer information" and "Enable Active OffsetCache" is not recommended for large consumers? I have about 30 consumers. Is 30 a larger number for consumers? Are there any possibility that this issue is related to larger number of consumers?

**Comment by patelh** [comment]
Are they kafka based or zookeeper based consumers?

**Comment by KaimingWan** [comment]
@patelh I have solved the issue. I used kafka based consumers. This issue is caused by running two kafka manager instances in the same time. I stopped one consumer and wait for a while, then everything become normal.
