### ISSUE TITLE
Rest-API 

### ISSUE THREAD

**Issue by rathinaganesh** [yahoo/kafka-manager#359]
Hi,

I am trying to find the set of REST-APIs available through the kafka-manager. I would like to use curl to query the data exposed through UI. 
Is there a place where I can find those exposed APIs? Or some documentation related to it.

Thanks.

**Comment by rathinaganesh** [comment]
Found the list of APIs available through conf/routes file. Not sure if there is any other better way to find all the APIs.

**Comment by chiwah-keen** [comment]
solved？

**Comment by kgupta26** [comment]
@rathinaganesh I dont know if the routes file will provide a solution.  We need to get apis that send non html responses..
