### ISSUE TITLE
Home page navbar-brand href does not use "play.http.context" prefix configuration

### ISSUE THREAD

**Issue by 4Clover** [yahoo/kafka-manager#363]
I am running Kafka Manager (1.3.1.8) from the Docker image provided by https://github.com/sheepkiller/kafka-manager-docker and running this behind HAProxy.  Since I have several web apps routed by HAProxy, I am using specific URIs for each application.  For KM, I am changing the application configuration file with a specific prefix context to support this scenario:

from:
`play.http.context = "/"`
to:
`play.http.context = "/kafka"`

With this configuration, KM behaves as expected with the exception of the home page.  The navigation bar on the home page sends the user to the wrong URL when clicked.  In my case, a 404 error page since the URI routing value is missing ("/").  It appears that the _href_ value is ignoring the context value that I have configured.

I am, however, finding that the navigation bar in other pages do have the configured setting.  For example, the cluster page works correctly.
`<a class="navbar-brand un-float-me" href="/kafka">Kafka Manager</a>`

Dug around in the code base; file app/views/navigation/clusterMenu.scala.html implements
`<a class="navbar-brand un-float-me" href="@routes.Application.index()">`
for the navigation bar, whereas file app/views/navigation/defaultMenu.scala.html does not
`<a class="navbar-brand un-float-me" href="/">Kafka Manager</a>`

Thanks.

**Comment by patelh** [comment]
fixed, try 1.3.3.4
