### ISSUE TITLE
Include sbt wrapper script?

### ISSUE THREAD

**Issue by miguno** [yahoo/kafka-manager#4]
Instead of requiring the user to have a system-wide installation of `sbt`, it is often preferable to include the [sbt wrapper script](https://github.com/paulp/sbt-extras/blob/master/sbt) from [sbt-extras](https://github.com/paulp/sbt-extras) (e.g. most Twitter Scala projects include this sbt wrapper).

The benefit is that the version of sbt configured in [build.properties](project/build.properties) will be downloaded automatically if needed.  The only change for users is that they must run sbt-related commands via `./sbt` instead of `sbt`.

**Comment by samklr** [comment]
Thought the same thing. I'm planning to run it inside a docker container ...

**Comment by patelh** [comment]
Good idea, will add it, thanks for the suggestion!

**Comment by miguno** [comment]
I'd also updated the README accordingly (https://github.com/yahoo/kafka-manager#deployment).

`sbt clean dist` should now be `./sbt clean dist`.
