### ISSUE TITLE
Kafka 0.11.* support

### ISSUE THREAD

**Issue by shayangz** [yahoo/kafka-manager#418]
Are there any plans for supporting the latest release?

It looks like as-is, if you point to a 0.11.* cluster you get an infinite number of these errors and chew up CPU

```
[warn] o.a.k.c.NetworkClient - Bootstrap broker ip:port disconnected
```

**Comment by andreybratus** [comment]
Actually it works on my local setup:
- Kafka 0.11.0.0
- Zookeeper 3.4.10
- Kafka-manager 1.3.3.8

I didn't test all the features, but basic things work:
- add/remove cluster
- I could see my broker and JMX metrics
- Create/delete topic
- Consumers and consumers lag

**Comment by bruciebruce** [comment]
Question for  andreybratus.  What did you choose for the kafka version in the pulldown?  There obviously is no 0.11 option...

![image](https://user-images.githubusercontent.com/493847/28880393-c54d2d38-7759-11e7-9b57-75c5cb9b8b8e.png)


Thanks.

**Comment by andreybratus** [comment]
@bruciebruce I chose the latest version available, which is 0.10.2.1.

![screen shot 2017-08-02 at 17 19 13](https://user-images.githubusercontent.com/6642048/28880945-d0ae18d4-77a6-11e7-83bd-52ba23c8fe87.png)

**Comment by shayangz** [comment]
It did connect for me as well at first glance. But when I left it running for a bit CPU continued to climb on the box. Looking at the logs I noticed a flurry of these errors

```
[warn] o.a.k.c.NetworkClient - Bootstrap broker ip:port disconnected
```

My guess is the protocol changes in 0.11.0.0 could be driving these disconnects.

@andreybratus, can you confirm you are not seeing these errors and no CPU hogging?

**Comment by andreybratus** [comment]
yes, I do confirm that I can't see any high or increasing CPU usage, neither errors or warnings in the logs.

my logs:
```
[info] k.m.l.LogkafkaViewCacheActor - Updating logkafka view...
[info] k.m.a.c.BrokerViewCacheActor - Updating broker view...
[info] k.m.a.KafkaManagerActor - Updating internal state...
[info] k.m.a.KafkaManagerActor - Updating internal state...
[info] k.m.a.KafkaManagerActor - Updating internal state...
[info] k.m.a.c.BrokerViewCacheActor - Updating broker view...
[info] k.m.l.LogkafkaViewCacheActor - Updating logkafka view...
[info] k.m.a.KafkaManagerActor - Updating internal state...
[info] k.m.u.AdminUtils - Topic creation {"version":1,"partitions":{"4":[0],"1":[0],"0":[0],"2":[0],"3":[0]}}
[info] k.m.a.KafkaManagerActor - Updating internal state...
```

**Comment by shayangz** [comment]
Thanks. The only "special" thing about my setup is using SSL. Will try to test with SSL turned off and see if the issue is stemming from that.

**Comment by patelh** [comment]
Are you providing SSL certs to kafka manager as command line arguements?  Security protocol configuration was just added to cluster config.  Use latest version.

**Comment by bruciebruce** [comment]
andreybratus, I took your advice.  UI works.  Thanks.

**Comment by shayangz** [comment]
Thanks @patelh. The per cluster config is awesome and solved my issue.

**Comment by mabeyratne** [comment]
How do you set ssl.truststore location and password to Kafka-Manager? I set them as JVM parameters but it is not working.
