### ISSUE TITLE
Bug when building

### ISSUE THREAD

**Issue by ekarlso** [yahoo/kafka-manager#46]
```
    5 artifacts copied, 0 already retrieved (24459kB/302ms)
```

[info] Loading project definition from /home/ubuntu/kafka-manager/project

[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  \* com.typesafe.sbt:sbt-native-packager:0.7.4 -> 1.0.0-M4
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to kafka-manager (in build file:/home/ubuntu/kafka-manager/)

**Comment by evanmeng** [comment]
My situation is a little different, when running `sbt clean dist`
```
:: retrieving :: org.scala-sbt#boot-app
	confs: [default]
	51 artifacts copied, 0 already retrieved (15709kB/60ms)
[info] Loading project definition from /Users/yimmeng/tmp/kafka-manager/project
```

The build just hung there when loading project definition...

**Comment by patelh** [comment]
Yea, the time it is frozen sbt is actually downloading libs on first run.  It should be faster the next run.
