### ISSUE TITLE
What does mean the 'Messages in /sec' in Metrics？

### ISSUE THREAD

**Issue by cnsugar** [yahoo/kafka-manager#461]
What does mean the 'Messages in /sec' in Metrics ？ Is it the number of messages or the number of bytes？

![image](https://user-images.githubusercontent.com/14772070/34358269-3f58c95a-ea89-11e7-8b3d-1f0c55780e9d.png)

**Comment by montana-ua** [comment]
This is TPS. In another words this are messages per second during 1/5/15 interval.

**Comment by cnsugar** [comment]
Thank you! It means there are 200/1000/900 messages per second during 1/5/15 interval，right?

**Comment by montana-ua** [comment]
@cnsugar yes

**Comment by cnsugar** [comment]
@montana-ua  Thank you very much!

**Comment by skdangi** [comment]
@montana-ua  I am hoping that this doesn't include replication traffic across nodes, only the messages coming from clients on leader partitions.

**Comment by montana-ua** [comment]
@skdangi I'm not a kafka manager developer and can't be sure in 100%. However, based on my long time experience and some tests I see that TPS in KM shows only incoming messages to a leader.

**Comment by skdangi** [comment]
@montana-ua Thanks for the comment. Same seems to our experience.
