### ISSUE TITLE
could not build project

### ISSUE THREAD

**Issue by linyongfu2013** [yahoo/kafka-manager#464]
due to the network issue , I can not build the project with sbt . so , can anyone so kind to just mail me a copy , my email is 『linc.2010@162.com』. thank you so much.

**Comment by DavidLiuXh** [comment]
use VPN to download jar for sbt ?

**Comment by linyongfu2013** [comment]
sorry forget to commet my solutions. I used this repo [https://github.com/Centaur/repox.git](url) to help download the dependencies, it's still very slow though, you need to try many times.
