### ISSUE TITLE
Bad root server path when setting different port

### ISSUE THREAD

**Issue by simPod** [yahoo/kafka-manager#466]
When running on macOS:
> kafka-manager-1.3.3.16 $ bin/kafka-manager -dHttp.port=9001

It throws error:
> Bad root server path: kafka-manager-1.3.3.16/-dHttp.port=9001

Is there anything I'm doing wrong?

**Comment by gena01** [comment]
Shouldn't that be -D instead of -d

**Comment by simPod** [comment]
eeeeer you're right. My bad

Thanks!
