### ISSUE TITLE
Question - What does red mean? 

### ISSUE THREAD

**Issue by spuder** [yahoo/kafka-manager#47]
For some reason, one of the topics shows up as red. 

![screenshot 2015-04-06 15 38 14](https://cloud.githubusercontent.com/assets/242382/7013011/11f0b080-dc73-11e4-8aea-8910259f4070.png)

I think this might be a bug in kafka-manager since this topic isn't currently marked for deletion or anything. 

What causes a topic to be marked red?

**Comment by patelh** [comment]
A topic is marked red if it is marked for deletion in Zookeeper.  I have seen cases where if you create a topic and then delete it and attempt to create a topic with the same name, it fails to create properly and just gets marked as deleted by Kafka controller in 0.8.2.1.  I will try to validate this tomorrow in my dev environment.

**Comment by spuder** [comment]
That actually is what happened. I deleted the topic 'ndstreamer' and stopped everything from pushing to that topic for a day so it would have time to purge out. 

I then made a new topic with the same name and started pushing to it again. Everything seemed fine for a day until it abruptly showed up red after the weekend.

Is there a way to 'unmark' a topic for deletion

**Comment by spuder** [comment]
Figured it out by looking at the source. When kafka marks a topic for deletion, it calls the ZkUtils.scala class and adds to zookeeper the following entry: `/admin/delete_topics`

https://github.com/apache/kafka/blob/5f3eb1cafaecee746641fa43945cc0762635a0bd/core/src/main/scala/kafka/utils/ZkUtils.scala#L46

I assume that if a topic appears in both `kafka/admin/delete_topics` and `kafka/config/toipcs` then it is `marked for deletion`. If the topic is in only one or the other then the topic is valid or deleted. 

I worked around the issue by removing the topic from the `delete_topics` directory in zookeeper


![screenshot 2015-04-08 10 59 46](https://cloud.githubusercontent.com/assets/242382/7050502/fb6a1e1a-ddde-11e4-9ffb-4e180e5593dd.png)
