### ISSUE TITLE
Add 1.0.1 and 1.1.0 as a valid versions

### ISSUE THREAD

**Issue by jmax01** [yahoo/kafka-manager#497]
Add 1.0.1 and 1.1.0 as a valid versions
https://www.apache.org/dist/kafka/1.0.1/RELEASE_NOTES.html
https://www.apache.org/dist/kafka/1.1.0/RELEASE_NOTES.html (http://kafka.apache.org/11/documentation.html#upgrade)

**Comment by yangl** [comment]
LGTM

**Comment by pichouk** [comment]
Since #519 is merged, I guess we are just waiting for a new release ?

**Comment by patelh** [comment]
Version 1.3.3.18 adds this support.
