### ISSUE TITLE
upgrade kafka liberary to 1.1.0 - KafkaAdminClient

### ISSUE THREAD

**Issue by icearn** [yahoo/kafka-manager#499]
Hi guys,

I am looking at the latest kafka admin client doc and noticed that current kafka-manager (1.3.3.17) is still using kafka admin client lib 0.10.0.1. I suspect this leads to some issues that in the case of connecting with latest kafka brokers, it stops displaying consumer group info - especially after added SASL and acl control to kafka topics.

Is there any plan to upgrade the kafka lib to the latest? I am new to scala, if anyone would like to guide me I would hope to contribute to this.

**Comment by patelh** [comment]
1.3.3.18 upgrades to 1.1.0
