### ISSUE TITLE
When to support kafka 1.1.0

### ISSUE THREAD

**Issue by happyshui** [yahoo/kafka-manager#505]
When to support kafka 1.1.0

**Comment by jmax01** [comment]
This duplicates #497

PR is here https://github.com/yahoo/kafka-manager/pull/498

**Comment by jkrauska** [comment]
@jmax01 Did you do the CLA thing they requested?  Seems they only will accept patches with that?

**Comment by jmax01** [comment]
@jkrauska yupper:  https://yahoocla.herokuapp.com/-/jmax01

**Comment by patelh** [comment]
Support is in 1.3.3.18
