### ISSUE TITLE
执行bin/kafka-manager，提示 command not found

### ISSUE THREAD

**Issue by JustCrazyHeart** [yahoo/kafka-manager#517]
先切换到目录中 => cd kafka-manager-1.3.3.17
然后执行 => sudo bin/kafka-manager
报错提示 => sudo: bin/kafka-manager: command not found

**Comment by httpstart** [comment]
sudo 启动 写全路径

**Comment by JustCrazyHeart** [comment]
路径没问题的，要么脚本有问题，要么环境缺什么

**Comment by aditimittal** [comment]
try using chmod 766 kafka-manager
