### ISSUE TITLE
Not recommended for large # of consumers. Why?

### ISSUE THREAD

**Issue by simPod** [yahoo/kafka-manager#524]
When adding a cluster, theres a checkbox with label

> Poll consumer information (Not recommended for large # of consumers)

I'm missing why it is not recommended, what are the consequences?

**Comment by patelh** [comment]
This doesn't work so well if polling via JMX.  Works fine if the consumers are all kafka consumers which is mostly true today, back in the day it was in ZK.

**Comment by simPod** [comment]
So do you think we should update the message?
