### ISSUE TITLE
great project!

### ISSUE THREAD

**Issue by bayroot22** [yahoo/kafka-manager#6]
Hi - I just deployed Kafka-manager today and it is pretty cool. It abstracts a lot of the day-to-day tasks into a slick webui. What type of effort would be involved if it included near real-time stats like msg/rates disk usage, cluster utilization... I was thinking it would by a nice enhancement.Thanks, Brendan

**Comment by patelh** [comment]
Hi Brendan, thank you for the feedback!  We hope you find it as useful as we do.  We'll be adding some enhancements like providing custom configs for topic creation, and possibily an alter topic operation.  We may also add support to manage storm-kafka checkpoints.  We'll see how difficult it is to add message rate per topic but yes that would be a nice stat.  For disk usage, and network utilization all our boxes have standard monitoring through an internal tool so it would be redundant for us.  Also, Kafka does not explose this information that I know of, maybe through JMX.

**Comment by patelh** [comment]
msg/sec and bytes/sec have been added by @Mogztter through JMX polling.  Topic size information to be added next via JMX (tracked in #58 ).  Closing issue.  Thanks for the feedback!
