### ISSUE TITLE
kafka Lag值为负数

### ISSUE THREAD

**Issue by yangleimiao** [yahoo/kafka-manager#604]
不知道在这提合不合适，最近遇到kafka 的Lag变成负数，而且消费方总在特定时段消费延迟，不知道两者有没有关系

**Comment by 1576584678** [comment]
> 不知道在这提合不合适，最近遇到kafka的滞变变负数，而且消费方总在特定时段消费延迟，不知道两者有没有关系

解决了吗？我们这边也遇到了。

**Comment by woozhijun** [comment]
> Lag是负数不是集群出了问题，没事，消费方延迟的问题还在用各种方法排查……

Lag负数是集群哪里的问题，有解决步骤？

**Comment by wangycc** [comment]
@aaldawoud https://github.com/yahoo/kafka-manager/issues/216
