### ISSUE TITLE
Use slimer variant of docker base image

### ISSUE THREAD

**Issue by ST-DDT** [yahoo/kafka-manager#617]
The current builds of the docker images are quite huge compared to other providers, would it be possible to also provider slimer variants?

https://hub.docker.com/r/kafkamanager/kafka-manager (1.3.3.22@341MB)
https://hub.docker.com/r/hlebalbau/kafka-manager (1.3.3.22@137MB)

You can do that by simply replacing the base image [here](https://github.com/yahoo/kafka-manager/blob/master/build.sbt#L77) with a `-slim` or `-alpine` one.

**Comment by linehrr** [comment]
@ST-DDT you can close this ticket due to the merge of https://github.com/yahoo/kafka-manager/commit/4ee373d12c0d4627aa2268dc3d47bc35eaccb675
