### ISSUE TITLE
Metrics not displaying

### ISSUE THREAD

**Issue by yzernik** [yahoo/kafka-manager#62]
I'm trying to see the metrics for a new topic that I created, but all the fields are empty.

![screen shot 2015-05-05 at 2 26 54 pm](https://cloud.githubusercontent.com/assets/890133/7483357/2fc778f6-f333-11e4-9b40-7c96a55c1182.png)

**Comment by Mogztter** [comment]
@yzernik Did you configure the jmx port on your broker ?

**Comment by yzernik** [comment]
Oh, thanks.
