### ISSUE TITLE
Can't create topic with Latest release 2.0.0.0 and 2.0.0.1

### ISSUE THREAD

**Issue by akashsethi24** [yahoo/kafka-manager#634]
Hi,

I ran the Kafka Manager with 2.0.0.0 and 2.0.0.1 but with both of them we are not able to create topic.
It returns 400 Bad Request in Network.

Please Have a look.

**Comment by akashsethi24** [comment]
@patelh @flyaruu  Please Have a Look

**Comment by patelh** [comment]
Fixed in 2.0.0.2
