### ISSUE TITLE
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed

### ISSUE THREAD

**Issue by maojing0609** [yahoo/kafka-manager#652]
i`m facing the problem.
application.log is bellow

2019-06-01 13:04:44,713 - [ERROR] o.a.k.c.NetworkClient - [Consumer clientId=consumer-8, groupId=KMOffsetCache-xxxxxxxxxx] Connection to node -4 (/xxxxxx:9093) failed authentication due to: SSL handshake failed
2019-06-01 13:04:44,713 - [WARN] k.m.a.c.KafkaManagedOffsetCache - Failed to process a message from offset topic on cluster PROD!
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed

and consumer.properties likes follow

[root@iZbp1gf15gbzzr0k4e2pyjZ kafka-manager-2.0.0.2]# cat conf/consumer.properties
#security.protocol=PLAINTEXT
#key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
#value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
security.protocol=SSL
ssl.truststore.location=/var/private/ssl/kafka/0620/client.truststore.jks
ssl.keystore.location=/var/private/ssl/kafka/0620/client.keystore.jks
ssl.keystore.password=mypassword
ssl.truststore.password=mypassword

the jks works well in my project, but cant works in kafka-manager2.0.0.2

Look forward to your favourable reply

**Comment by nhathatrinh** [comment]
I wonder if it is possible to add a configuration to ignore hostnameVerifier for SSL?

**Comment by nhathatrinh** [comment]
The default value for ssl.endpoint.identification.algorithm is changed to https in kafka 2.0.0, which performs hostname verification (man-in-the-middle attacks are possible otherwise). Set ssl.endpoint.identification.algorithm to an empty string to restore the previous behaviour.

ssl.endpoint.identification.algorithm=
