### ISSUE TITLE
"Consumer Instance Owner" is empty

### ISSUE THREAD

**Issue by atulrenapurkar** [yahoo/kafka-manager#691]
When I am trying to user kafka-manager (2.0.0.2) and Kafka (2.3.0), "Consumer Instance Owner" is not visible in kafka-manager.
I am using application.conf as below. We are not using any environment variables. Could you please suggest us if I am doing anything wrong.
With Kafka(2.0.0) and Kafka-manager (1.3.3.21) we are able to see "Consumer Instance Owner" with same configuration. Feel free if you need any other information.

I am attaching screenshot as attachment for your reference .
<img width="1289" alt="Screen Shot 2019-09-26 at 3 33 35 PM" src="https://user-images.githubusercontent.com/13038482/65721624-606d8b80-e078-11e9-871a-43dc75d0db06.png">

play.crypto.secret="^<csmm5Fx4d=r2HEX8pelM3iBkFVv?k[mc;IZE<_Qoq8EkX_/7@Zt6dP05Pzea3U"
play.crypto.secret=${?APPLICATION_SECRET}
play.http.session.maxAge="1h"

# The application languages
# ~~~~~
play.i18n.langs=["en"]

play.http.requestHandler = "play.http.DefaultHttpRequestHandler"
play.http.context = "/"
play.application.loader=loader.KafkaManagerLoader

kafka-manager.zkhosts="XXXXXX1:2181,XXXXXX2:2181,XXXXXX3:2181"
#kafka-manager.zkhosts=${?ZK_HOSTS}
pinned-dispatcher.type="PinnedDispatcher"
pinned-dispatcher.executor="thread-pool-executor"
application.features=["KMClusterManagerFeature","KMTopicManagerFeature","KMPreferredReplicaElectionFeature","KMReassignPartitionsFeature"]
#application.features=["KMClusterManagerFeature","KMPreferredReplicaElectionFeature","KMReassignPartitionsFeature"]

akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
}

akka.logger-startup-timeout = 60s

basicAuthentication.enabled=true
basicAuthentication.enabled=${?KAFKA_MANAGER_AUTH_ENABLED}

basicAuthentication.ldap.enabled=false
basicAuthentication.ldap.enabled=${?KAFKA_MANAGER_LDAP_ENABLED}
basicAuthentication.ldap.server=""
basicAuthentication.ldap.server=${?KAFKA_MANAGER_LDAP_SERVER}
basicAuthentication.ldap.port=389
basicAuthentication.ldap.port=${?KAFKA_MANAGER_LDAP_PORT}
basicAuthentication.ldap.username=""
basicAuthentication.ldap.username=${?KAFKA_MANAGER_LDAP_USERNAME}
basicAuthentication.ldap.password=""
basicAuthentication.ldap.password=${?KAFKA_MANAGER_LDAP_PASSWORD}
basicAuthentication.ldap.search-base-dn=""
basicAuthentication.ldap.search-base-dn=${?KAFKA_MANAGER_LDAP_SEARCH_BASE_DN}
basicAuthentication.ldap.search-filter="(uid=$capturedLogin$)"
basicAuthentication.ldap.search-filter=${?KAFKA_MANAGER_LDAP_SEARCH_FILTER}
basicAuthentication.ldap.connection-pool-size=10
basicAuthentication.ldap.connection-pool-size=${?KAFKA_MANAGER_LDAP_CONNECTION_POOL_SIZE}
basicAuthentication.ldap.ssl=false
basicAuthentication.ldap.ssl=${?KAFKA_MANAGER_LDAP_SSL}

basicAuthentication.username="AAAAAAA"
basicAuthentication.username=${?KAFKA_MANAGER_USERNAME}
basicAuthentication.password="BBBBBB"
basicAuthentication.password=${?KAFKA_MANAGER_PASSWORD}

basicAuthentication.realm="Kafka-Manager"
basicAuthentication.excluded=["/api/health"] # ping the health of your instance without authentification

kafka-manager.consumer.properties.file=${?CONSUMER_PROPERTIES_FILE}

**Comment by mirsafari** [comment]
Hello @atulrenapurkar 
I've stumbled across same issue with the same software versions. Can you please explain how did you fix this issue?

**Comment by ShrushtiPatel** [comment]
Hi @mirsafari @atulrenapurkar I've stumbled across the same issue with the same software versions. Can you please explain how did you fix it?

**Comment by mirsafari** [comment]
Hi. I did not manage to find a workaround
