### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by aaronzirbes** [yahoo/kafka-manager#77]
Please tag your releases to make it check out a release version.

```
git tag 1.2.2
git push --tags
```

Thanks!

**Comment by aaronzirbes** [comment]
I was able to find the old ones using this command:
```
git log --full-diff -p build.sbt |grep -E '^(\+version :=|^commit )' |grep -B 1 '+version'
```

**Comment by aaronzirbes** [comment]
The tags are available on my fork: https://github.com/aaronzirbes/kafka-manager/tree/1.2.4 if you want to pull them down and then just push to upstream

**Comment by patelh** [comment]
I pushed all tags from 1.2.*.  Thanks!
