### ISSUE TITLE
Topic and consumer offset details

### ISSUE THREAD

**Issue by raags** [yahoo/kafka-manager#80]
Hi, Can we get the topic and consumer offsets on the dashboard? With this we can also calculate the lag for a consumer.

**Comment by gianluca-sabena** [comment]
+1

**Comment by heliu0328** [comment]
+1

**Comment by KevinJMao** [comment]
+1

**Comment by zfrank** [comment]
+1

**Comment by zheolong** [comment]
+1

**Comment by kaolian** [comment]
+1

**Comment by MichaelScofield** [comment]
+1

**Comment by udoprog** [comment]
+1, this is the last feature I'm still using ConsumerOffsetChecker for.

**Comment by blue20080** [comment]
+1

**Comment by puneetgoyal11** [comment]
+1... it will be really good if we have Consumer offset information in tool

**Comment by tonyxuqqi** [comment]
+1

**Comment by aseev-xx** [comment]
+1

**Comment by patelh** [comment]
This has been added.  Please build off master. Thanks to @cvcal and @nzhang1220

**Comment by aseev-xx** [comment]
@patelh thank you very much, good job!

**Comment by vvarma** [comment]
Would storm consumer offsets be a good fit in this project?

**Comment by zheolong** [comment]
@raags Close this issue please.
